[build]
  command = "npm install"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/cors-proxy/:splat"
  status = 200
  force = true
